name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

#permissions:
 # contents: write

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md
    - name: Remove composer lock
      run: rm composer.lock
    - name: maj
      run: composer install --no-dev --optimize-autoloader
    
    - name: Setup PHPunit
      run: composer install -n

    - name: Install Google Cloud Storage
      run: composer require google/cloud-storage
    
    #- name: hey
      #run: echo $PWD/../
      #run: ../vendor/bin/phpunit --coverage-text=test2 
      #env:
      # XDEBUG_MODE: coverage
       # extensions-cache-key-name: phpextensions
     # working-directory: tst
    #- name: hey2
      #run: cat test2
     # working-directory: tst
    - name: installation de codesniffe
      run: composer require --dev squizlabs/php_codesniffer
    - name: test sniffer
      run: ../vendor/bin/phpcs .
      #working-directory: tst
    #- name: rectification erreur
     # run: ../vendor/bin/phpcbf .
     # working-directory: tst
          # composer installation

    # - name: Run test suite
    #   run: composer run-script test

