name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md
    - name: maj
      run: composer install --no-dev --optimize-autoloader
    
    - name: Setup PHPunit
      run: composer install -n

    - name: Install Google Cloud Storage
      run: composer require google/cloud-storage
    
    - name: hey
      #run: echo $PWD/../
      run: phpunit --coverage-text=test 
      working-directory: tst
          # composer installation

    # - name: Run test suite
    #   run: composer run-script test
    env:
      extensions: gd, sqlite3, xdebug
